#!/usr/bin/env python3
"""
Neutron - MIUI 14 Mod Toolkit for Xiaomi Redmi 10 2022 (selene)
Optimized debloat, performance, battery, and display tweaks.

Usage:
    python install.py                # Interactive menu
    python install.py --all          # Apply everything
    python install.py --debloat      # Debloat only
    python install.py --perf         # Performance only
    python install.py --battery      # Battery only
    python install.py --display      # Display only
    python install.py --restore      # Restore backup
    python install.py --backup       # Backup only
"""

import os
import sys
import platform
import subprocess
import argparse
import json
import shutil
from pathlib import Path

TOOL_NAME = "Neutron"
TOOL_VERSION = "1.0.0"
DEVICE = "selene"
VENDOR = "xiaomi"

NEUTRON_DIR = Path(__file__).parent
BACKUP_DIR = NEUTRON_DIR / "backups"

TWEAKS = {
    "debloat": {
        "description": "Remove MIUI bloatware and telemetry",
        "packages_to_remove": [
            "com.miui.player",
            "com.miui.video",
            "com.miui.gallery",  
            "com.miui.calculator",
            "com.miui.compass",
            "com.miui.fm",
            "com.miui.screenrecorder",
            "com.miui.weather2",
            "com.miui.notes",
            "com.miui.mishare.connectivity",
            "com.xiaomi.misettings",
            "com.miui.daemon",
            "com.miui.hybrid",
            "com.miui.personalassistant",
            "com.milink.service",
            "com.xiaomi.finddevice",
            "com.miui.miwallpaper",
            "com.miui.guardprovider",
            "com.miui.securityadd",
            "com.google.android.youtube",
            "com.google.android.music",
            "com.google.android.videos",
        ],
        "services_to_disable": [
            "miui.daemon",
            "miui.analytics",
            "misight",
        ],
    },
    "perf": {
        "description": "Performance optimization tweaks",
        "build_prop": {
            "ro.vendor.qti.cgroup_follow.enable": "1",
            "persist.sys.NEON": "true",
            "ro.iorwapd.enable": "false",
            "debug.sf.latch_unsignaled": "1",
            "debug.renderengine.backend": "skiagl",
            "debug.hwui.renderer": "skiagl",
            "ro.config.alarm_alert": "vibra.ogg",
            "persist.radio.apm_sim_not_pwdn": "1",
            "ro.ril.power_collapse": "1",
            "windows.animation.scale": "0.5",
            "transition.animation.scale": "0.5",
            "animator.duration.scale": "0.5",
        },
    },
    "battery": {
        "description": "Battery optimization tweaks",
        "build_prop": {
            "powersave.enabled": "1",
            "ro.config.alarm_alert": "vibra.ogg",
            "ro.ril.power_collapse": "1",
            "persist.radio.apm_sim_not_pwdn": "1",
            "deviceidle.disabled": "false",
            "ro.vendor.qti.cgroup_follow.enable": "1",
        },
    },
    "display": {
        "description": "Display tweaks (90Hz, rendering)",
        "build_prop": {
            "ro.surface_flinger.max_frame_buffer_acquired_buffers": "3",
            "debug.sf.fps": "90",
            "debug.sf.latch_unsignaled": "1",
            "debug.renderengine.backend": "skiagl",
            "ro.surface_flinger.running_without_sync_framework": "true",
        },
    },
    "memory": {
        "description": "RAM/ZRAM optimization (great for 4GB models)",
        "build_prop": {
            "ro.config.zram": "true",
            "ro.lmk.critical_upgrade": "true",
            "ro.lmk.upgrade_pressure": "100",
            "ro.lmk.downgrade_pressure": "100",
        },
    },
}

BASH_TEMPLATE = """#!/bin/bash
# Neutron MIUI 14 Mod - {description}
# Device: Xiaomi Redmi 10 2022 (selene)
# Generated by Neutron v{version}

set -e

ADB="adb"
PROPS_FILE="$(dirname "$0")/../core/tweaks.json"

echo "============================================"
echo "  Neutron v{version} - {description}"
echo "============================================"
echo ""

# Check ADB
if ! command -v $ADB &> /dev/null; then
    echo "[!] ADB not found. Install Android platform-tools."
    exit 1
fi

# Check device
echo "[*] Checking for device..."
$ADB wait-for-device
SERIAL=$($ADB shell getprop ro.serialno 2>/dev/null | tr -d '\\r')
echo "[+] Device found: $SERIAL"

# Check root
ROOT_CHECK=$($ADB shell id 2>/dev/null | tr -d '\\r')
if [[ "$ROOT_CHECK" != *"uid=0"* ]]; then
    echo "[!] Device not rooted. Trying su..."
    $ADB shell "su -c 'id'" 2>/dev/null | grep -q "uid=0" || {{
        echo "[!] Root required. Please root your device first."
        exit 1
    }}
    SU="su -c"
else
    SU=""
fi

# Remount
echo "[*] Remounting system as read-write..."
$ADB shell "$SU mount -o remount,rw /" 2>/dev/null || true
$ADB shell "$SU mount -o remount,rw /vendor" 2>/dev/null || true

{script_body}

echo ""
echo "[+] Done! Reboot recommended."
echo "    Run: adb reboot"
"""

POWERSHELL_TEMPLATE = """<#
.SYNOPSIS
    Neutron MIUI 14 Mod - {description}
.DESCRIPTION
    Device: Xiaomi Redmi 10 2022 (selene)
    Generated by Neutron v{version}
#>

$ErrorActionPreference = "Stop"

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Neutron v{version} - {description}" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Check ADB
$adb = Get-Command adb -ErrorAction SilentlyContinue
if (-not $adb) {{
    Write-Host "[!] ADB not found. Install Android platform-tools and add to PATH." -ForegroundColor Red
    exit 1
}}

# Check device
Write-Host "[*] Checking for device..." -ForegroundColor Yellow
adb wait-for-device
$serial = (adb shell getprop ro.serialno 2>$null).Trim()
Write-Host "[+] Device found: $serial" -ForegroundColor Green

# Check root
Write-Host "[*] Checking root access..." -ForegroundColor Yellow
$rootCheck = adb shell "su -c 'id' 2>/dev/null"
if ($rootCheck -notmatch "uid=0") {{
    Write-Host "[!] Root required. Please root your device first." -ForegroundColor Red
    exit 1
}}

# Remount
Write-Host "[*] Remounting system partitions..." -ForegroundColor Yellow
adb shell "su -c 'mount -o remount,rw /'" 2>$null
adb shell "su -c 'mount -o remount,rw /vendor'" 2>$null

{script_body}

Write-Host ""
Write-Host "[+] Done! Reboot recommended." -ForegroundColor Green
Write-Host "    Run: adb reboot" -ForegroundColor Gray
"""


def get_platform():
    system = platform.system().lower()
    if system == "windows":
        return "windows"
    elif system == "darwin":
        return "macos"
    else:
        return "linux"


def check_adb():
    try:
        result = subprocess.run(
            ["adb", "version"], capture_output=True, text=True, timeout=5
        )
        return "Android Debug Bridge" in result.stdout
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def check_device():
    try:
        result = subprocess.run(
            ["adb", "devices"], capture_output=True, text=True, timeout=5
        )
        lines = result.stdout.strip().split("\n")
        devices = [l for l in lines[1:] if l.strip() and "device" in l]
        return len(devices) > 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def adb_shell(cmd):
    try:
        result = subprocess.run(
            ["adb", "shell", cmd], capture_output=True, text=True, timeout=30
        )
        return result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return ""


def backup_vendor():
    print("[*] Creating backup...")
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    backup_path = BACKUP_DIR / "vendor_backup"
    
    print(f"    Backing up vendor partition...")
    subprocess.run(["adb", "shell", "su -c 'dd if=/dev/block/by-name/vendor of=/sdcard/vendor_backup.img'"], timeout=300)
    subprocess.run(["adb", "pull", "/sdcard/vendor_backup.img", str(backup_path)], timeout=300)
    subprocess.run(["adb", "shell", "rm /sdcard/vendor_backup.img"], timeout=30)
    
    print(f"[+] Backup saved to: {backup_path}")
    return backup_path


def generate_debloat_bash():
    packages = TWEAKS["debloat"]["packages_to_remove"]
    services = TWEAKS["debloat"]["services_to_disable"]
    
    lines = ['# Remove bloatware packages', 'echo "[*] Removing bloatware..."']
    for pkg in packages:
        lines.append(f'$ADB shell "$SU pm uninstall -k --user 0 {pkg}" 2>/dev/null && echo "    Removed: {pkg}" || echo "    Skipped: {pkg}"')
    
    lines.append('')
    lines.append('# Disable telemetry services')
    lines.append('echo "[*] Disabling telemetry..."')
    for svc in services:
        lines.append(f'$ADB shell "$SU pm disable {svc}" 2>/dev/null && echo "    Disabled: {svc}" || echo "    Skipped: {svc}"')
    
    lines.append('echo "[+] Debloat complete!"')
    return '\n'.join(lines)


def generate_debloat_powershell():
    packages = TWEAKS["debloat"]["packages_to_remove"]
    services = TWEAKS["debloat"]["services_to_disable"]
    
    lines = ['# Remove bloatware packages', 'Write-Host "[*] Removing bloatware..." -ForegroundColor Yellow']
    for pkg in packages:
        lines.append(f'adb shell "su -c \\"pm uninstall -k --user 0 {pkg}\\"" 2>$null; Write-Host "    Removed: {pkg}" -ForegroundColor Gray')
    
    lines.append('')
    lines.append('# Disable telemetry')
    lines.append('Write-Host "[*] Disabling telemetry..." -ForegroundColor Yellow')
    for svc in services:
        lines.append(f'adb shell "su -c \\"pm disable {svc}\\"" 2>$null; Write-Host "    Disabled: {svc}" -ForegroundColor Gray')
    
    lines.append('Write-Host "[+] Debloat complete!" -ForegroundColor Green')
    return '\n'.join(lines)


def generate_prop_bash(tweak_name):
    props = TWEAKS[tweak_name]["build_prop"]
    lines = [f'# Apply {tweak_name} tweaks', f'echo "[*] Applying {tweak_name} tweaks..."']
    
    for key, value in props.items():
        lines.append(f'$ADB shell "$SU sed -i /^{key}/d /vendor/build.prop"')
        lines.append(f'$ADB shell "$SU echo \\"{key}={value}\\" >> /vendor/build.prop"')
        lines.append(f'echo "    Set: {key}={value}"')
    
    lines.append(f'echo "[+] {tweak_name.capitalize()} tweaks applied!"')
    return '\n'.join(lines)


def generate_prop_powershell(tweak_name):
    props = TWEAKS[tweak_name]["build_prop"]
    lines = [f'# Apply {tweak_name} tweaks', f'Write-Host "[*] Applying {tweak_name} tweaks..." -ForegroundColor Yellow']
    
    for key, value in props.items():
        lines.append(f'adb shell "su -c \\"sed -i /^{key}/d /vendor/build.prop\\""')
        lines.append(f'adb shell "su -c \\"echo {key}={value} >> /vendor/build.prop\\""')
        lines.append(f'Write-Host "    Set: {key}={value}" -ForegroundColor Gray')
    
    lines.append(f'Write-Host "[+] {tweak_name.capitalize()} tweaks applied!" -ForegroundColor Green')
    return '\n'.join(lines)


def generate_restore_bash():
    return """# Restore vendor backup
echo "[*] Restoring vendor backup..."
BACKUP="$(dirname "$0")/../backups/vendor_backup.img"
if [ ! -f "$BACKUP" ]; then
    echo "[!] No backup found at $BACKUP"
    echo "    Please restore vendor manually via SP Flash Tool."
    exit 1
fi

echo "[*] Flashing vendor backup..."
$ADB shell "$SU dd if=/sdcard/vendor_backup.img of=$(ls /dev/block/by-name/vendor 2>/dev/null || echo /dev/block/platform/bootdevice/by-name/vendor)"
echo "[+] Vendor restored! Reboot recommended."
"""


def generate_restore_powershell():
    return """# Restore vendor backup
Write-Host "[*] Restoring vendor backup..." -ForegroundColor Yellow
$backup = Join-Path (Split-Path $PSScriptRoot) "backups\\vendor_backup.img"
if (-not (Test-Path $backup)) {
    Write-Host "[!] No backup found at $backup" -ForegroundColor Red
    Write-Host "    Please restore vendor manually via SP Flash Tool." -ForegroundColor Gray
    exit 1
}

adb push $backup /sdcard/vendor_backup.img
Write-Host "[+] Vendor restored! Reboot recommended." -ForegroundColor Green
"""


def write_script(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="\n") as f:
        f.write(content)
    if get_platform() != "windows":
        os.chmod(path, 0o755)


def install_all(platform_name):
    print(f"\n[*] Installing ALL tweaks via {platform_name} scripts...")
    
    if platform_name == "windows":
        debloat = POWERSHELL_TEMPLATE.format(
            description=TWEAKS["debloat"]["description"],
            version=TOOL_VERSION,
            script_body=generate_debloat_powershell()
        )
        write_script(NEUTRON_DIR / "windows" / "debloat.ps1", debloat)
        
        perf = POWERSHELL_TEMPLATE.format(
            description=TWEAKS["perf"]["description"],
            version=TOOL_VERSION,
            script_body=generate_prop_powershell("perf")
        )
        write_script(NEUTRON_DIR / "windows" / "perf.ps1", perf)
        
        battery = POWERSHELL_TEMPLATE.format(
            description=TWEAKS["battery"]["description"],
            version=TOOL_VERSION,
            script_body=generate_prop_powershell("battery")
        )
        write_script(NEUTRON_DIR / "windows" / "battery.ps1", battery)
        
        display = POWERSHELL_TEMPLATE.format(
            description=TWEAKS["display"]["description"],
            version=TOOL_VERSION,
            script_body=generate_prop_powershell("display")
        )
        write_script(NEUTRON_DIR / "windows" / "display.ps1", display)
        
        restore = POWERSHELL_TEMPLATE.format(
            description="Restore vendor backup",
            version=TOOL_VERSION,
            script_body=generate_restore_powershell()
        )
        write_script(NEUTRON_DIR / "windows" / "restore.ps1", restore)
        
        # All-in-one
        all_body = (
            generate_debloat_powershell() + "\n\n" +
            generate_prop_powershell("perf") + "\n\n" +
            generate_prop_powershell("battery") + "\n\n" +
            generate_prop_powershell("display") + "\n\n" +
            generate_prop_powershell("memory")
        )
        all_tweaks = POWERSHELL_TEMPLATE.format(
            description="Apply ALL tweaks",
            version=TOOL_VERSION,
            script_body=all_body
        )
        write_script(NEUTRON_DIR / "windows" / "install_all.ps1", all_tweaks)
        
    else:
        shell = "bash"
        template = BASH_TEMPLATE
        
        debloat = template.format(
            description=TWEAKS["debloat"]["description"],
            version=TOOL_VERSION,
            script_body=generate_debloat_bash()
        )
        ext = ".sh"
        folder = platform_name
        write_script(NEUTRON_DIR / folder / "debloat" + ext, debloat)
        
        perf = template.format(
            description=TWEAKS["perf"]["description"],
            version=TOOL_VERSION,
            script_body=generate_prop_bash("perf")
        )
        write_script(NEUTRON_DIR / folder / "perf" + ext, perf)
        
        battery = template.format(
            description=TWEAKS["battery"]["description"],
            version=TOOL_VERSION,
            script_body=generate_prop_bash("battery")
        )
        write_script(NEUTRON_DIR / folder / "battery" + ext, battery)
        
        display = template.format(
            description=TWEAKS["display"]["description"],
            version=TOOL_VERSION,
            script_body=generate_prop_bash("display")
        )
        write_script(NEUTRON_DIR / folder / "display" + ext, display)
        
        restore = template.format(
            description="Restore vendor backup",
            version=TOOL_VERSION,
            script_body=generate_restore_bash()
        )
        write_script(NEUTRON_DIR / folder / "restore" + ext, restore)
        
        all_body = (
            generate_debloat_bash() + "\n\n" +
            generate_prop_bash("perf") + "\n\n" +
            generate_prop_bash("battery") + "\n\n" +
            generate_prop_bash("display") + "\n\n" +
            generate_prop_bash("memory")
        )
        all_tweaks = template.format(
            description="Apply ALL tweaks",
            version=TOOL_VERSION,
            script_body=all_body
        )
        write_script(NEUTRON_DIR / folder / "install_all" + ext, all_tweaks)
    
    print(f"[+] Scripts generated for {platform_name}!")


def interactive_menu():
    current_os = get_platform()
    
    print(f"""
    ╔══════════════════════════════════════════╗
    ║     Neutron v{TOOL_VERSION} - MIUI 14 Mod       ║
    ║     Device: Xiaomi Redmi 10 2022         ║
    ║     Codename: selene                     ║
    ╚══════════════════════════════════════════╝
    
    Detected OS: {current_os.upper()}
    ADB: {'Connected' if check_adb() else 'NOT FOUND'}
    Device: {'Connected' if check_device() else 'NOT FOUND'}
    
    Available tweaks:
    [1] Backup vendor
    [2] Debloat (remove MIUI bloatware)
    [3] Performance tweaks
    [4] Battery tweaks  
    [5] Display tweaks (90Hz)
    [6] Memory/ZRAM tweaks
    [7] Apply ALL tweaks
    [8] Restore vendor backup
    [0] Exit
    """)
    
    choice = input("    Select option: ").strip()
    
    if choice == "1":
        backup_vendor()
    elif choice == "2":
        install_all(current_os)
        print(f"\n    Run: ./{current_os}/debloat.{('ps1' if current_os == 'windows' else 'sh')}")
    elif choice == "3":
        install_all(current_os)
        print(f"\n    Run: ./{current_os}/perf.{('ps1' if current_os == 'windows' else 'sh')}")
    elif choice == "4":
        install_all(current_os)
        print(f"\n    Run: ./{current_os}/battery.{('ps1' if current_os == 'windows' else 'sh')}")
    elif choice == "5":
        install_all(current_os)
        print(f"\n    Run: ./{current_os}/display.{('ps1' if current_os == 'windows' else 'sh')}")
    elif choice == "6":
        install_all(current_os)
        print(f"\n    Run: ./{current_os}/memory.{('ps1' if current_os == 'windows' else 'sh')}")
    elif choice == "7":
        install_all(current_os)
        print(f"\n    Run: ./{current_os}/install_all.{('ps1' if current_os == 'windows' else 'sh')}")
    elif choice == "8":
        install_all(current_os)
        print(f"\n    Run: ./{current_os}/restore.{('ps1' if current_os == 'windows' else 'sh')}")
    elif choice == "0":
        print("    Goodbye!")
        sys.exit(0)
    else:
        print("    Invalid option.")


def main():
    parser = argparse.ArgumentParser(
        description=f"{TOOL_NAME} v{TOOL_VERSION} - MIUI 14 Mod Toolkit for {DEVICE}"
    )
    parser.add_argument("--all", action="store_true", help="Apply all tweaks")
    parser.add_argument("--debloat", action="store_true", help="Debloat only")
    parser.add_argument("--perf", action="store_true", help="Performance tweaks")
    parser.add_argument("--battery", action="store_true", help="Battery tweaks")
    parser.add_argument("--display", action="store_true", help="Display tweaks")
    parser.add_argument("--memory", action="store_true", help="Memory/ZRAM tweaks")
    parser.add_argument("--backup", action="store_true", help="Backup vendor")
    parser.add_argument("--restore", action="store_true", help="Restore vendor backup")
    parser.add_argument("--generate", choices=["windows", "linux", "macos", "all"], 
                       help="Generate scripts for platform")
    
    args = parser.parse_args()
    
    if any([args.all, args.debloat, args.perf, args.battery, args.display, 
            args.memory, args.backup, args.restore, args.generate]):
        
        if args.generate:
            if args.generate == "all":
                for p in ["windows", "linux", "macos"]:
                    install_all(p)
            else:
                install_all(args.generate)
            return
        
        if not check_adb():
            print("[!] ADB not found. Install Android platform-tools.")
            sys.exit(1)
        
        if not check_device():
            print("[!] No device connected. Check USB debugging.")
            sys.exit(1)
        
        if args.backup:
            backup_vendor()
        if args.all or args.debloat:
            install_all(get_platform())
        if args.all or args.perf:
            install_all(get_platform())
        if args.all or args.battery:
            install_all(get_platform())
        if args.all or args.display:
            install_all(get_platform())
        if args.all or args.memory:
            install_all(get_platform())
        if args.restore:
            install_all(get_platform())
    else:
        interactive_menu()


if __name__ == "__main__":
    main()
