// Shim for audio.primary.mt6768.so
// Provides android::FormatConverter::mTable[] symbol

#include <system/audio.h>

struct FormatConverter {
    const char *name;
    audio_format_t format;
};

// Full table of AUDIO_FORMAT_* mappings
extern "C" FormatConverter android_FormatConverter_mTable[] = {
    {"AUDIO_FORMAT_INVALID", AUDIO_FORMAT_INVALID},
    {"AUDIO_FORMAT_NONE", AUDIO_FORMAT_NONE},
    {"AUDIO_FORMAT_PCM_16_BIT", AUDIO_FORMAT_PCM_16_BIT},
    {"AUDIO_FORMAT_PCM_8_BIT", AUDIO_FORMAT_PCM_8_BIT},
    {"AUDIO_FORMAT_PCM_32_BIT", AUDIO_FORMAT_PCM_32_BIT},
    {"AUDIO_FORMAT_PCM_8_24_BIT", AUDIO_FORMAT_PCM_8_24_BIT},
    {"AUDIO_FORMAT_PCM_FLOAT", AUDIO_FORMAT_PCM_FLOAT},
    {"AUDIO_FORMAT_PCM_24_BIT_PACKED", AUDIO_FORMAT_PCM_24_BIT_PACKED},
    {"AUDIO_FORMAT_AAC_LC", AUDIO_FORMAT_AAC_LC},
    {"AUDIO_FORMAT_AAC_HE_V1", AUDIO_FORMAT_AAC_HE_V1},
    {"AUDIO_FORMAT_AAC_HE_V2", AUDIO_FORMAT_AAC_HE_V2},
    {"AUDIO_FORMAT_AAC_LD", AUDIO_FORMAT_AAC_LD},
    {"AUDIO_FORMAT_AAC_HE_LD", AUDIO_FORMAT_AAC_HE_LD},
    {"AUDIO_FORMAT_AAC_ELD", AUDIO_FORMAT_AAC_ELD},
    {"AUDIO_FORMAT_AAC_XHE", AUDIO_FORMAT_AAC_XHE},
    {"AUDIO_FORMAT_MP3", AUDIO_FORMAT_MP3},
    {"AUDIO_FORMAT_AMR_NB", AUDIO_FORMAT_AMR_NB},
    {"AUDIO_FORMAT_AMR_WB", AUDIO_FORMAT_AMR_WB},
    {"AUDIO_FORMAT_GSM_AMR", AUDIO_FORMAT_GSM_AMR},
    {"AUDIO_FORMAT_VORBIS", AUDIO_FORMAT_VORBIS},
    {"AUDIO_FORMAT_OPUS", AUDIO_FORMAT_OPUS},
    {"AUDIO_FORMAT_AC3", AUDIO_FORMAT_AC3},
    {"AUDIO_FORMAT_E_AC3", AUDIO_FORMAT_E_AC3},
    {"AUDIO_FORMAT_DTS", AUDIO_FORMAT_DTS},
    {"AUDIO_FORMAT_DTS_HD", AUDIO_FORMAT_DTS_HD},
    {"AUDIO_FORMAT_FLAC", AUDIO_FORMAT_FLAC},
    {"AUDIO_FORMAT_IEC61937", AUDIO_FORMAT_IEC61937},
    {"AUDIO_FORMAT_EVRC", AUDIO_FORMAT_EVRC},
    {"AUDIO_FORMAT_EVRCB", AUDIO_FORMAT_EVRCB},
    {"AUDIO_FORMAT_EVRCWB", AUDIO_FORMAT_EVRCWB},
    {"AUDIO_FORMAT_EVRCNW", AUDIO_FORMAT_EVRCNW},
    {"AUDIO_FORMAT_QCELP", AUDIO_FORMAT_QCELP},
    {"AUDIO_FORMAT_WMA", AUDIO_FORMAT_WMA},
    {"AUDIO_FORMAT_MIDI", AUDIO_FORMAT_MIDI},
};
