name: Configure Crave Runner

on:
  workflow_dispatch:
    inputs:
      RUNNER_TOKEN:
        description: 'GitHub self-hosted runner token (NOT a PAT)'
        required: true

jobs:
  configure-runner:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tmux
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux

      - name: Configure crave CLI
        run: |
          if [[ $DCDEVSPACE == *1* ]]; then
            echo 'Already in devspace'
          else
            mkdir -p ${HOME}/bin/
            curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
            mv ${PWD}/crave ${HOME}/bin/
            sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
            envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
            rm -rf ${PWD}/crave.conf.sample
          fi
        env:
          CRAVE_USERNAME: ${{ secrets.CRAVE_USERNAME }}
          CRAVE_TOKEN: ${{ secrets.CRAVE_TOKEN }}

      - name: Start Crave devspace and configure runner
        run: |
          crave ${{ secrets.CRAVE_FLAGS }} devspace -- "
            rm -rf actions-runner || true
            curl https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/scripts/runner-setup.sh | bash
            if [[ '${{ inputs.RUNNER_TOKEN }}' == github_pat_* ]]; then
              echo 'PAT does not work!'
              exit 1
            fi
            cd actions-runner
            ./config.sh --unattended --url 'https://github.com/${{ github.repository }}' --token '${{ inputs.RUNNER_TOKEN }}'
          "
